### ISSUE TITLE
Update Glossarium Version

### ISSUE THREAD

**Issue by JanEhehalt** [lbsekr/provadis-typst-template#8]
Hallo liebe Leute, ich finde euer Projekt wirklich cool und bin dankbar, dass ich das nicht selbst machen muss. Ich würde vorschlagen auf die neuste Version von Glossarium (0.4.1) zu updaten, um auch die neusten Features nutzen zu können. 
Außerdem werden Abkürzungen von der alten Version so dargestellt: DTAG (_Deutsche Telekom AG_)
In der neueren Version so: Deutsche Telekom AG (DTAG)
Die neue Darstellung ist denke ich eher state of the art oder? 🗿

gl hf und immer weiter machen (iterieren 👺👺👺)

**Comment by lbsekr** [comment]
Danke für den Reminder, wird gemacht. Aber wenn du willst mach du dasgerne. Änder das auf `
8-update-glossarium-version ` und wir mergen das dann
